/**
 * @file melodies.h
 * @brief This file contains the different melodies that can be played by the HP output pin
 * @brief The melodies are stored in an array of frequencies with a fixed known sampling
 * @brief the array a generated by a python script that uses an FFT to extract the frequencies from a sound file
 * @author A. Frayard
 */


#define MELODY_FREQ 40


#define C0 16
#define C0_SHARP 17
#define D0 18
#define D0_SHARP 19
#define E0 20
#define F0 21
#define F0_SHARP 23
#define G0 24
#define G0_SHARP 25
#define A0 27
#define A0_SHARP 29
#define B0 30

#define C1 32
#define C1_SHARP 34
#define D1 36
#define D1_SHARP 38
#define E1 41
#define F1 43
#define F1_SHARP 46
#define G1 49
#define G1_SHARP 51
#define A1 55
#define A1_SHARP 58
#define B1 61

#define C2 65
#define C2_SHARP 69
#define D2 73
#define D2_SHARP 77
#define E2 82
#define F2 87
#define F2_SHARP 92
#define G2 98
#define G2_SHARP 103
#define A2 110
#define A2_SHARP 116
#define B2 123

#define C3 130
#define C3_SHARP 138
#define D3 146
#define D3_SHARP 155
#define E3 164
#define F3 174
#define F3_SHARP 185
#define G3 196
#define G3_SHARP 207
#define A3 220
#define A3_SHARP 233
#define B3 246

#define C4 261
#define C4_SHARP 277
#define D4 293
#define D4_SHARP 311
#define E4 329
#define F4 349
#define F4_SHARP 369
#define G4 392
#define G4_SHARP 415
#define A4 440
#define A4_SHARP 466
#define B4 493

#define C5 523
#define C5_SHARP 554
#define D5 587
#define D5_SHARP 622
#define E5 659
#define F5 698
#define F5_SHARP 739
#define G5 783
#define G5_SHARP 830
#define A5 880
#define A5_SHARP 932
#define B5 987

#define C6 1046
#define C6_SHARP 1108
#define D6 1174
#define D6_SHARP 1244
#define E6 1318
#define F6 1396
#define F6_SHARP 1480
#define G6 1568
#define G6_SHARP 1661
#define A6 1760
#define A6_SHARP 1865
#define B6 1976

#define C7 2093
#define C7_SHARP 2217
#define D7 2349
#define D7_SHARP 2489
#define E7 2637
#define F7 2793
#define F7_SHARP 2960
#define G7 3136
#define G7_SHARP 3322
#define A7 3520
#define A7_SHARP 3729
#define B7 3951

#define C8 4186
#define C8_SHARP 4435
#define D8 4699
#define D8_SHARP 4978
#define E8 5274
#define F8 5588
#define F8_SHARP 5919
#define G8 6272
#define G8_SHARP 6645
#define A8 7040
#define A8_SHARP 7459
#define B8 7902

#define REST 0



 /**
  * @brief test melody with 1Hz sampling
  */
 alt_u16 melody_2[] = {
   C4, D4, E4, F4, G4, A4,
   B4, C5, D5, E5, F5, G5,
   A5, B5, C6, D6, E6, F6,
   G6, A6, B6, C7, D7, E7,
   F7, G7, A7, B7, C8, D8,
 };


  /**
  * @brief test melody with 1Hz sampling
  */
 alt_u16 melody_3[] = {
  500, 500, 500, 500, 500,
  500, 500, 500, 500, 500
 };

 alt_u16 melody_1[] = {
  659, 494, 523, 587, 523, 494, 440, 440,
  523, 659, 587, 523, 494, 523, 587, 659,
  523, 440, 440, 440, 587, 698, 880, 784,
  698, 659, 523, 587, 659, 523, 440, 494,
  523, 659, 494, 523, 587, 523, 494, 440
 };


